language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

# command to install dependencies
install: "pip install -r requirements_dev.txt"
# command to run tests
script: coverage run setup.py test
